/**
 * Server instructions for db-mcp (SQLite MCP Server).
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
 *     Edit src/constants/server-instructions.md instead,
 *     then run: npm run generate:instructions
 *
 * These instructions are automatically sent to MCP clients during initialization,
 * providing guidance for AI agents on tool usage.
 *
 * Optimized for token efficiency with tiered instruction levels.
 */

import type { ToolGroup } from "../types/index.js";
import { TOOL_GROUPS, ALL_TOOL_GROUPS } from "../filtering/tool-constants.js";

/**
 * Resource definition for instruction generation
 */
export interface ResourceDefinition {
  uri: string;
  name: string;
  description?: string;
}

/**
 * Prompt definition for instruction generation
 */
export interface PromptDefinition {
  name: string;
  description?: string;
}

/**
 * Instruction detail level for token efficiency
 * - essential: ~1K tokens - Core behaviors only (for token-constrained clients)
 * - standard: ~1.2K tokens - + Tool filtering and groups (default)
 * - full: ~4.1K tokens - + Complete tool/resource reference
 */
export type InstructionLevel = "essential" | "standard" | "full";

/**
 * Essential behavioral guidance (~1K tokens)
 * Core patterns every AI agent should follow.
 */
const ESSENTIAL_INSTRUCTIONS = `# db-mcp (SQLite MCP Server)

## Quick Access

| Purpose         | Action                     |
| --------------- | -------------------------- |
| Health check    | \`server_health\` tool       |
| Server info     | \`server_info\` tool         |
| List adapters   | \`list_adapters\` tool       |
| Database schema | \`sqlite://schema\` resource |
| List tables     | \`sqlite://tables\` resource |

## Built-in Tools (always available)

| Tool            | Description                                            |
| --------------- | ------------------------------------------------------ |
| \`server_info\`   | Get server name, version, adapters, tool filter config |
| \`server_health\` | Check adapter connections, latency, SQLite version     |
| \`list_adapters\` | List registered database adapters                      |

## Core Tools (9)

| Tool                    | Description                                                                  |
| ----------------------- | ---------------------------------------------------------------------------- |
| \`sqlite_read_query\`     | Execute SELECT queries                                                       |
| \`sqlite_write_query\`    | Execute INSERT/UPDATE/DELETE                                                 |
| \`sqlite_list_tables\`    | List tables with column counts (excludeSystemTables hides SpatiaLite tables) |
| \`sqlite_describe_table\` | Get table schema                                                             |
| \`sqlite_create_table\`   | Create new table                                                             |
| \`sqlite_drop_table\`     | Drop (delete) a table                                                        |
| \`sqlite_get_indexes\`    | List indexes (use excludeSystemIndexes to hide SpatiaLite indexes)           |
| \`sqlite_create_index\`   | Create index                                                                 |
| \`sqlite_drop_index\`     | Drop (delete) an index                                                       |

## WASM vs Native

| Feature                                           | Native                | WASM        | Fallback         |
| ------------------------------------------------- | --------------------- | ----------- | ---------------- |
| FTS5 full-text search                             | ✅                    | ❌          | None             |
| Transactions (7 tools)                            | ✅                    | ❌          | None             |
| Window functions (6 tools in stats group)         | ✅                    | ❌          | None             |
| SpatiaLite GIS (7 tools; 4 basic geo always work) | ✅                    | ❌          | None             |
| Backup/Restore (3 tools)                          | ✅                    | ❌          | Graceful error   |
| R-Tree spatial indexing                           | ✅                    | ❌          | Graceful error   |
| CSV virtual tables                                | ✅                    | ❌          | Graceful error   |
| generate_series                                   | JS fallback           | JS fallback | —                |
| dbstat                                            | ✅ native (per-table) | ❌          | JS (counts only) |
| soundex()                                         | ✅ native             | ❌          | JS               |

## Code Mode (1 tool)

| Tool                  | Description                                                       |
| --------------------- | ----------------------------------------------------------------- |
| \`sqlite_execute_code\` | Execute JavaScript in a sandboxed environment with \`sqlite.*\` API |

**Usage**: \`sqlite_execute_code({ code: "const tables = await sqlite.core.listTables(); return tables;" })\`
**Discover**: \`sqlite.help()\` for all groups, \`sqlite.<group>.help()\` for methods.
**Groups**: \`sqlite.core\`, \`sqlite.json\`, \`sqlite.text\`, \`sqlite.stats\`, \`sqlite.vector\`, \`sqlite.admin\`, \`sqlite.geo\``;

/**
 * Tool filtering instructions (~200 additional tokens)
 */
const FILTERING_INSTRUCTIONS = `\n## Tool Filtering

Available presets via \`--tool-filter\`:
| Shortcut | WASM | Native | Use Case |
|----------|------|--------|----------|
| \`starter\` | 45 | 49 | ⭐ Recommended: Core(8) + JSON(23) + Text(13-17*) + Codemode(1) |
| \`analytics\` | 45 | 51 | Core(8) + JSON(23) + Stats(19: 13 core + 6 window) + Codemode(1) |
| \`search\` | 33 | 37 | Core(8) + Text(13-17*) + Vector(11) + Codemode(1) |
| \`spatial\` | 24 | 31 | Core(8) + Geo(4-11) + Vector(11) + Codemode(1) |
| \`minimal\` | 9 | 9 | Core(8) + Codemode(1) |
| \`full\` | 99 | 123 | All tools |

_+3 built-in tools (\`server_info\`, \`server_health\`, \`list_adapters\`) always included_

**Groups**: \`core\`, \`json\`, \`text\`, \`stats\`, \`vector\`, \`admin\`, \`geo\`, \`codemode\`
**Syntax**: \`"core,json"\` (whitelist), \`"+stats"\` (add), \`"-admin"\` (remove)
_Text group: 17 native, 13 in WASM (4 FTS5 tools require native)_`;

/**
 * Tool reference - comprehensive usage examples
 */
const TOOL_REFERENCE = `\n## ⚠️ Critical Gotchas

1. **sqlite_write_query**: ⛔ Only INSERT/UPDATE/DELETE — use \`sqlite_read_query\` for SELECT
2. **Regex patterns**: Double-escape backslashes (\`\\\\\\\\\`) when passing through JSON/MCP
3. **FTS5 virtual tables**: \`*_fts\` and shadow tables \`*_fts_*\` are hidden from \`sqlite_list_tables\` for cleaner output
4. **FTS5 boolean logic**: Uses AND by default — \`"machine learning"\` = rows with BOTH words. Use OR explicitly: \`"machine OR learning"\`
5. **FTS5 rebuild**: After \`sqlite_fts_create\`, must call \`sqlite_fts_rebuild\` to populate index with existing data
6. **json_each row multiplication**: Expands arrays to rows — use \`limit\` param for large arrays
7. **json_group_object without groupByColumn**: Each row creates a key-value pair; duplicate keys result if key values aren't unique
8. **allowExpressions**: For column extraction ONLY (e.g., \`json_extract\`), NOT aggregate functions — use \`aggregateFunction\` param instead
9. **sqlite_json_normalize_column**: Defaults to \`preserve\` (maintains original format); use \`outputFormat: 'text'\` to force text
10. **Fuzzy matching tokenization**: Matches WORD TOKENS by default — \`"laptop"\` matches \`"Laptop Pro 15"\` (distance 0 on first token). Use \`tokenize: false\` for full-string matching
11. **SpatiaLite distances**: \`nearest_neighbor\`/\`distance_matrix\` return CARTESIAN distance (degrees), not geodetic (km/miles)
12. **SpatiaLite buffer**: Auto-simplifies output by default (tolerance=0.0001). Use \`simplifyTolerance: 0\` to disable
13. **sqlite_stats_top_n**: ⚠️ Always use \`selectColumns\` to avoid returning all columns (large payloads with text fields)
14. **CSV virtual tables**: Require ABSOLUTE file paths
15. **sqlite_create_series_table**: Creates a REGULAR table (not virtual) — use \`sqlite_drop_table\` to remove
16. **sqlite_dbstat**: \`summarize\` only works in native; WASM returns counts only
17. **PRAGMA compile options**: WASM may show FTS3, not FTS5

## JSON Operations (23 tools)

- \`sqlite_create_json_collection({ tableName, indexes: [{ path: "$.key" }] })\` — creates table with JSON indexes
- \`sqlite_json_insert({ table, column, data: {...} })\` — insert JSON document
- \`sqlite_json_query({ table, column, filterPaths: { "$.key": value }, selectPaths: ["$.path"] })\` — query with filters
- \`sqlite_json_extract({ table, column, path })\` — extract value at path. Returns null if path doesn't exist
- \`sqlite_json_set({ table, column, path, value, whereClause })\` — set value at path
- \`sqlite_json_merge({ table, column, mergeData: {...}, whereClause })\` — merge object into existing
- \`sqlite_json_remove\` — remove key at path
- \`sqlite_json_array_append({ table, column, path, value, whereClause })\` — append to array
- \`sqlite_json_each({ table, column, path, limit })\` — expand array to rows (⚠️ multiplies output)
- \`sqlite_json_group_array({ table, valueColumn, groupByColumn, allowExpressions? })\` — group values into arrays. For JSON collections: use \`allowExpressions: true\` with \`json_extract(col, '$.path')\` for both value and group columns
- \`sqlite_json_group_object({ table, keyColumn, aggregateFunction? })\` — group into key-value object. For aggregate values (COUNT, SUM, AVG), use \`aggregateFunction\` param
- \`sqlite_json_analyze_schema({ table, column })\` — infer schema types
- \`sqlite_json_storage_info({ table, column })\` — check text vs JSONB format
- \`sqlite_jsonb_convert({ table, column })\` — convert to JSONB for faster queries (SQLite 3.45+)

## Vector/Semantic Search (11 tools)

- \`sqlite_vector_create_table({ tableName, dimensions, additionalColumns: [{ name, type }] })\` — create vector table
- \`sqlite_vector_store({ table, idColumn, vectorColumn, id, vector: [...] })\` — store single vector
- \`sqlite_vector_batch_store({ table, idColumn, vectorColumn, items: [{ id, vector }] })\` — batch store
- \`sqlite_vector_search({ table, vectorColumn, queryVector: [...], limit, returnColumns: ["id", "title"] })\` — search vectors. \`returnColumns\` omits vector data for smaller payloads
- \`sqlite_vector_get({ table, idColumn, vectorColumn, id })\` — returns parsed \`vector\` array + raw JSON string in \`metadata\`
- \`sqlite_vector_delete({ table, idColumn, ids: [1, 2, 3] })\` — delete vectors
- \`sqlite_vector_count({ table, dimensions? })\` — count vectors
- \`sqlite_vector_dimensions({ table, vectorColumn })\` — get dimensions
- \`sqlite_vector_stats({ table, vectorColumn })\` — magnitude min/max/avg
- \`sqlite_vector_normalize({ vector: [...] })\` — returns unit vector
- \`sqlite_vector_distance({ vector1, vector2, metric: "cosine" })\` — or \`"euclidean"\`, \`"dot"\`

## Full-Text Search / FTS5 (4 tools, Native only)

- \`sqlite_fts_create({ tableName, sourceTable, columns: ["title", "content"] })\` — creates FTS5 table with auto-sync triggers
- \`sqlite_fts_rebuild({ table })\` — ⚠️ Required after create to populate index with existing data
- \`sqlite_fts_search({ table, query, limit })\` — search FTS5 index. AND by default; use \`OR\` explicitly
- \`sqlite_fts_count\` — count FTS5 entries

## Statistical Analysis (13 core + 6 window)

Core (always available):
- \`sqlite_stats_basic({ table, column })\` — count, sum, avg, min, max
- \`sqlite_stats_percentile({ table, column, percentiles: [25, 50, 75, 90] })\`
- \`sqlite_stats_histogram({ table, column, buckets: 10 })\`
- \`sqlite_stats_regression({ table, xColumn, yColumn, degree? })\` — linear (default) or quadratic (\`degree: 2\`)
- \`sqlite_stats_outliers({ table, column, method: "iqr" })\` — or \`"zscore"\`
- \`sqlite_stats_top_n({ table, column, n, selectColumns: ["id", "name", "price"] })\` — ⚠️ always use \`selectColumns\`
- \`sqlite_stats_hypothesis({ table, column, testType: "ttest_one", expectedMean })\` — hypothesis testing
- \`sqlite_stats_correlation\`, \`sqlite_stats_covariance\`, \`sqlite_stats_frequency\`, \`sqlite_stats_summary\`, \`sqlite_stats_z_score\`, \`sqlite_stats_moving_average\`

Window functions (Native only):
- \`sqlite_window_row_number({ table, orderBy, partitionBy? })\`
- \`sqlite_window_rank({ table, orderBy, partitionBy?, rankType: "dense_rank" })\`
- \`sqlite_window_running_total({ table, valueColumn, orderBy })\`
- \`sqlite_window_moving_avg({ table, valueColumn, orderBy, windowSize: 7 })\`
- \`sqlite_window_lead_lag\`, \`sqlite_window_ntile\`

## Geospatial Operations (4 basic + 7 SpatiaLite)

Basic geo (always available — Haversine formula):
- \`sqlite_geo_distance({ lat1, lon1, lat2, lon2 })\` — returns km
- \`sqlite_geo_bounding_box({ table, latColumn, lonColumn, minLat, maxLat, minLon, maxLon })\`
- \`sqlite_geo_nearby({ table, latColumn, lonColumn, centerLat, centerLon, radius, unit: "km" })\`
- \`sqlite_geo_cluster({ table, latColumn, lonColumn, gridSize })\`

SpatiaLite (Native only):
- \`sqlite_spatialite_create_table({ tableName, geometryColumn, geometryType: "POINT", srid: 4326 })\`
- \`sqlite_spatialite_import({ tableName, format: "wkt"|"geojson", data, additionalData? })\`
- \`sqlite_spatialite_query({ query: "SELECT name, AsText(geom) FROM places WHERE..." })\`
- \`sqlite_spatialite_analyze({ analysisType, sourceTable, geometryColumn })\` — types: \`spatial_extent\`, \`point_in_polygon\`, \`nearest_neighbor\`, \`distance_matrix\`. ⚠️ nearest_neighbor/distance_matrix return CARTESIAN distance. Use \`excludeSelf: true\` for same source/target table
- \`sqlite_spatialite_transform({ operation, geometry1, distance })\` — operations: \`buffer\`, \`simplify\`. Buffer \`distance\` = radius; simplify \`distance\` = tolerance (0.0001 for lat/lon). Buffer auto-simplifies (use \`simplifyTolerance: 0\` to disable)
- \`sqlite_spatialite_index({ tableName, geometryColumn, action: "create" })\`
- \`sqlite_spatialite_status\` — check SpatiaLite availability

## Transactions (7 tools, Native only)

- \`sqlite_transaction_execute({ statements: ["UPDATE a SET x=1", "UPDATE b SET y=2"] })\` — atomic execution
- \`sqlite_transaction_begin({ mode: "immediate" })\`
- \`sqlite_transaction_savepoint({ name })\` / \`sqlite_transaction_rollback_to({ name })\` / \`sqlite_transaction_release({ name })\`
- \`sqlite_transaction_commit()\` / \`sqlite_transaction_rollback()\`

## Text Processing (13 core + 4 FTS5)

- \`sqlite_regex_match({ table, column, pattern })\` — ⚠️ double-escape backslashes in JSON
- \`sqlite_regex_extract({ table, column, pattern, groupIndex })\` — extract capture group
- \`sqlite_text_split({ table, column, delimiter })\` — split into parts array
- \`sqlite_text_concat({ table, columns: ["first", "last"], separator: " " })\`
- \`sqlite_text_normalize({ table, column, mode: "strip_accents" })\` — or nfc, nfd, nfkc, nfkd
- \`sqlite_text_validate({ table, column, pattern: "email" })\` — patterns: email, phone, url, uuid, ipv4, custom. For custom: \`pattern: "custom", customPattern: "^[A-Z]{2}[0-9]{4}$"\`
- \`sqlite_fuzzy_match({ table, column, search, maxDistance, tokenize? })\` — matches WORD TOKENS by default. Use \`tokenize: false\` for full-string matching
- \`sqlite_phonetic_match({ table, column, search, algorithm: "soundex" })\` — matches against any word in value. Use \`includeRowData: false\` for lighter payloads
- \`sqlite_advanced_search({ table, column, searchTerm, techniques: ["exact", "fuzzy", "phonetic"], fuzzyThreshold })\` — fuzzyThreshold: 0.3-0.4 = loose, 0.6-0.8 = strict
- \`sqlite_text_pad\`, \`sqlite_text_template\`, \`sqlite_text_similarity\`, \`sqlite_text_word_count\`

## Database Administration

Maintenance:
- \`sqlite_integrity_check({ maxErrors })\` — check for corruption
- \`sqlite_optimize({ analyze?, reindex? })\` — optimize performance
- \`sqlite_vacuum()\` — reclaim space
- \`sqlite_analyze({ table? })\` — update statistics for query planner
- \`sqlite_dbstat({ summarize? })\` — storage stats (⚠️ \`summarize\` native-only; WASM returns counts only)

Backup/Restore (Native only):
- \`sqlite_backup({ targetPath })\` — backup database
- \`sqlite_verify_backup({ backupPath })\` — check integrity without restoring
- \`sqlite_restore({ sourcePath })\` — ⚠️ WARNING: Replaces current database

PRAGMA:
- \`sqlite_pragma_settings({ pragma, value? })\` — get/set PRAGMA values
- \`sqlite_pragma_table_info({ table })\` — column details
- \`sqlite_pragma_compile_options({ filter? })\` — filter compile options (⚠️ WASM may show FTS3, not FTS5)
- \`sqlite_pragma_database_list()\` — list attached databases
- \`sqlite_pragma_optimize()\` — run PRAGMA optimize

Index & Stats:
- \`sqlite_index_stats({ table })\` — stats for explicit indexes

Views:
- \`sqlite_create_view({ viewName, selectQuery, replace? })\` — \`replace: true\` for CREATE OR REPLACE
- \`sqlite_list_views()\` — list all views
- \`sqlite_drop_view({ viewName })\`

Virtual tables:
- \`sqlite_list_virtual_tables()\` — list FTS5, R-Tree, CSV tables
- \`sqlite_virtual_table_info({ tableName })\` — module and column info
- \`sqlite_drop_virtual_table({ tableName, ifExists? })\`

Generate series (pure JS):
- \`sqlite_generate_series({ start, stop, step? })\` — returns array of values
- \`sqlite_create_series_table({ tableName, start, stop })\` — creates REGULAR table (use \`sqlite_drop_table\` to remove)

R-Tree (Native only):
- \`sqlite_create_rtree_table({ tableName, dimensions: 2 })\` — 2D: minX, maxX, minY, maxY. Returns graceful error in WASM

CSV Virtual Tables (Native only, requires ABSOLUTE paths):
- \`sqlite_analyze_csv_schema({ filePath })\` — analyze CSV structure
- \`sqlite_create_csv_table({ tableName, filePath })\` — create virtual table from CSV

Business insights:
- \`sqlite_append_insight({ insight })\` — add to \`memo://insights\`

## Code Mode API Mapping

\`sqlite_group_action\` → \`sqlite.group.action()\` (group prefixes dropped: \`sqlite_json_insert\` → \`sqlite.json.insert()\`)

**Positional args work**: \`sqlite.core.readQuery("SELECT...")\`, \`sqlite.json.insert("docs", "data", {...})\`

**Discovery**: \`sqlite.help()\` returns all groups and methods. \`sqlite.core.help()\`, \`sqlite.json.help()\` for group-specific methods.`;

/**
 * Generate dynamic instructions based on enabled tools, resources, and prompts
 *
 * @param enabledTools - Set of enabled tool names
 * @param resources - Available resource definitions
 * @param prompts - Available prompt definitions
 * @param level - Instruction detail level (default: 'standard')
 */
export function generateInstructions(
  enabledTools: Set<string>,
  _resources: ResourceDefinition[],
  prompts: PromptDefinition[],
  level: InstructionLevel = "standard",
): string {
  let instructions = ESSENTIAL_INSTRUCTIONS;

  // Standard and full levels include filtering patterns
  if (level === "standard" || level === "full") {
    instructions += FILTERING_INSTRUCTIONS;
  }

  // Full level includes complete tool reference
  if (level === "full") {
    instructions += TOOL_REFERENCE;

    // Add active tools summary
    const activeGroups = getActiveToolGroups(enabledTools);
    if (activeGroups.length > 0) {
      instructions += `\n## Active Tools (${String(enabledTools.size)})\n`;
      for (const { group, tools } of activeGroups) {
        instructions += `**${group}**: ${tools.map((t) => `\\\`${t}\\\``).join(", ")}\n`;
      }
    }

    // Add prompts section
    if (prompts.length > 0) {
      instructions += `\n## Prompts (${String(prompts.length)})\n`;
      instructions += "Pre-built templates and guided workflows:\n";
      for (const prompt of prompts) {
        instructions += `- \\\`${prompt.name}\\\` - ${prompt.description ?? ""}\n`;
      }
    }
  }

  return instructions;
}

/**
 * Get active tool groups with their enabled tools
 */
function getActiveToolGroups(
  enabledTools: Set<string>,
): { group: ToolGroup; tools: string[] }[] {
  const activeGroups: { group: ToolGroup; tools: string[] }[] = [];

  for (const group of ALL_TOOL_GROUPS) {
    const allTools = TOOL_GROUPS[group];
    const enabledInGroup = allTools.filter((tool) => enabledTools.has(tool));
    if (enabledInGroup.length > 0) {
      activeGroups.push({ group, tools: enabledInGroup });
    }
  }

  return activeGroups;
}

/**
 * Static instructions for backward compatibility
 * @deprecated Use generateInstructions() instead for dynamic content
 */
export const SERVER_INSTRUCTIONS =
  ESSENTIAL_INSTRUCTIONS + FILTERING_INSTRUCTIONS;
