/**
 * Server instructions for db-mcp (SQLite MCP Server).
 *
 * ⚠️  AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
 *     Edit src/constants/server-instructions/*.md instead,
 *     then run: npm run generate:instructions
 *
 * Slim instructions are sent to MCP clients during initialization.
 * Detailed help is available on-demand via sqlite://help resources.
 */

/**
 * Slim instructions for the MCP instructions field (~600 chars).
 * Points agents to sqlite://help resources for detailed reference.
 */
export const INSTRUCTIONS = `# db-mcp (SQLite MCP Server)

## Quick Access

| Purpose         | Action                     |
| --------------- | -------------------------- |
| Health check    | \`server_health\` tool       |
| Server info     | \`server_info\` tool         |
| Database schema | \`sqlite://schema\` resource |
| Tool help       | \`sqlite://help\` resource   |

## Built-in Tools

\`server_info\`, \`server_health\`, \`list_adapters\` — always available.

## Help Resources

Read \`sqlite://help\` for gotchas and critical usage patterns.
Read \`sqlite://help/{group}\` for group-specific tool reference (json, text, stats, vector, geo, admin, introspection, migration).
Only help resources for your enabled tool groups are registered.`;

/**
 * Help content keyed by group name.
 * 'gotchas' is the always-available help (sqlite://help).
 * Other keys are tool groups (sqlite://help/{group}).
 */
export const HELP_CONTENT: ReadonlyMap<string, string> = new Map([
  [
    "admin",
    `# db-mcp Help — Database Administration (33 Native / 26 WASM)

## Transactions (7 tools, Native only)

\`\`\`javascript
// Atomic multi-statement execution (preferred for simple cases)
sqlite_transaction_execute({ statements: ["UPDATE a SET x=1", "UPDATE b SET y=2"] });

// Manual transaction control
sqlite_transaction_begin({ mode: "immediate" }); // or "deferred", "exclusive"
sqlite_transaction_savepoint({ name: "checkpoint" });
sqlite_transaction_rollback_to({ name: "checkpoint" });
sqlite_transaction_release({ name: "checkpoint" });
sqlite_transaction_commit();
sqlite_transaction_rollback();
\`\`\`

## Maintenance

\`\`\`javascript
sqlite_integrity_check({ maxErrors: 10 }); // check for corruption
sqlite_optimize({ analyze: true, reindex: true }); // optimize performance
sqlite_vacuum(); // reclaim space
sqlite_analyze({ table: "orders" }); // update statistics for query planner
sqlite_dbstat({ summarize: true }); // storage stats (⚠️ summarize native-only; WASM returns counts only)
\`\`\`

## Backup/Restore (Native only)

\`\`\`javascript
sqlite_backup({ targetPath: "/path/to/backup.db" });
sqlite_verify_backup({ backupPath: "/path/to/backup.db" }); // check integrity without restoring
sqlite_restore({ sourcePath: "/path/to/backup.db" }); // ⚠️ WARNING: Replaces current database
\`\`\`

## PRAGMA

\`\`\`javascript
sqlite_pragma_settings({ pragma: "journal_mode" }); // get value
sqlite_pragma_settings({ pragma: "cache_size", value: 10000 }); // set value
sqlite_pragma_table_info({ table: "users" }); // column details
sqlite_pragma_compile_options({ filter: "FTS" }); // ⚠️ WASM may show FTS3, not FTS5
sqlite_pragma_database_list(); // list attached databases
sqlite_pragma_optimize(); // run PRAGMA optimize
\`\`\`

## Index & Stats

- \`sqlite_index_stats({ table: "orders" })\` — stats for explicit indexes

## Views

\`\`\`javascript
sqlite_create_view({ viewName: "active_orders", selectQuery: "SELECT * FROM orders WHERE status = 'active'" });
sqlite_create_view({ viewName: "v", selectQuery: "...", replace: true }); // CREATE OR REPLACE
sqlite_list_views(); // list all views
sqlite_drop_view({ viewName: "active_orders" });
\`\`\`

## Virtual Tables

\`\`\`javascript
sqlite_list_virtual_tables(); // list FTS5, R-Tree, CSV tables
sqlite_virtual_table_info({ tableName: "articles_fts" }); // module and column info
sqlite_drop_virtual_table({ tableName: "old_fts", ifExists: true });
\`\`\`

## Generate Series (pure JS)

\`\`\`javascript
sqlite_generate_series({ start: 1, stop: 100, step: 5 }); // returns array of values
// ⚠️ Creates a REGULAR table (not virtual) — use sqlite_drop_table to remove
sqlite_create_series_table({ tableName: "numbers", start: 1, stop: 1000 });
\`\`\`

## R-Tree (Native only)

\`\`\`javascript
sqlite_create_rtree_table({ tableName: "locations_idx", dimensions: 2 }); // 2D: minX, maxX, minY, maxY
// Returns graceful error with wasmLimitation: true in WASM
\`\`\`

## CSV Virtual Tables (Native only)

⚠️ Requires ABSOLUTE file paths

\`\`\`javascript
sqlite_analyze_csv_schema({ filePath: "/absolute/path/to/data.csv" }); // analyze CSV structure
sqlite_create_csv_table({ tableName: "csv_data", filePath: "/absolute/path/to/data.csv" });
\`\`\`

## Business Insights

\`\`\`javascript
sqlite_append_insight({ insight: "Q4 revenue increased 23% YoY" }); // add to memo://insights
\`\`\``,
  ],
  [
    "geo",
    `# db-mcp Help — Geospatial Operations (4 basic + 7 SpatiaLite)

## Basic Geo (always available — Haversine formula)

\`\`\`javascript
sqlite_geo_distance({ lat1: 40.7128, lon1: -74.006, lat2: 34.0522, lon2: -118.2437 }); // returns km
sqlite_geo_bounding_box({
  table: "stores", latColumn: "lat", lonColumn: "lon",
  minLat: 40, maxLat: 41, minLon: -75, maxLon: -73,
});
sqlite_geo_nearby({
  table: "stores", latColumn: "lat", lonColumn: "lon",
  centerLat: 40.7, centerLon: -74, radius: 10, unit: "km",
});
sqlite_geo_cluster({ table: "customers", latColumn: "lat", lonColumn: "lon", gridSize: 0.1 });
\`\`\`

## SpatiaLite (7 tools, Native only)

\`\`\`javascript
// Load extension first
sqlite_spatialite_load(); // ⚠️ Required before using other spatial tools

// Create spatial table with geometry column
sqlite_spatialite_create_table({ tableName: "places", geometryColumn: "geom", geometryType: "POINT", srid: 4326 });

// Import data (WKT or GeoJSON)
sqlite_spatialite_import({ tableName: "places", format: "wkt", data: "POINT(-73.99 40.75)", additionalData: { name: "NYC" } });
sqlite_spatialite_import({ tableName: "places", format: "geojson", data: '{"type":"Point","coordinates":[-73.99,40.75]}' });

// Spatial queries (SELECT only)
sqlite_spatialite_query({ query: "SELECT name, AsText(geom) FROM places WHERE ST_Within(geom, ...)" });

// Spatial analysis
// analysisType: "spatial_extent" | "point_in_polygon" | "nearest_neighbor" | "distance_matrix"
// ⚠️ nearest_neighbor/distance_matrix return CARTESIAN distance (degrees), not geodetic (km/miles)
// For same source/target table, use excludeSelf: true to avoid self-matches
sqlite_spatialite_analyze({ analysisType: "spatial_extent", sourceTable: "places", geometryColumn: "geom" });
sqlite_spatialite_analyze({ analysisType: "nearest_neighbor", sourceTable: "pts", targetTable: "pts", excludeSelf: true });

// Geometry transforms
// buffer: 'distance' = radius; simplify: 'distance' = tolerance (0.0001 for lat/lon)
// ⚠️ Buffer auto-simplifies output by default (tolerance=0.0001). Use simplifyTolerance: 0 to disable
sqlite_spatialite_transform({ operation: "buffer", geometry1: "POINT(-73.99 40.75)", distance: 0.01 });
sqlite_spatialite_transform({ operation: "simplify", geometry1: "...", distance: 0.001 });

// Spatial index (R-Tree)
sqlite_spatialite_index({ tableName: "places", geometryColumn: "geom", action: "create" }); // create, drop, or check
\`\`\``,
  ],
  [
    "gotchas",
    `# db-mcp Help — Gotchas & Code Mode

## ⚠️ Critical Gotchas

1. **sqlite_write_query**: ⛔ Only INSERT/UPDATE/DELETE — use \`sqlite_read_query\` for SELECT
2. **Regex patterns**: Double-escape backslashes (\`\\\\\\\\\`) when passing through JSON/MCP
3. **FTS5 virtual tables**: \`*_fts\` and shadow tables \`*_fts_*\` are hidden from \`sqlite_list_tables\` for cleaner output
4. **FTS5 boolean logic**: Uses AND by default — \`"machine learning"\` = rows with BOTH words. Use OR explicitly: \`"machine OR learning"\`
5. **FTS5 rebuild**: After \`sqlite_fts_create\`, must call \`sqlite_fts_rebuild\` to populate index with existing data
6. **json_each row multiplication**: Expands arrays to rows — use \`limit\` param for large arrays
7. **json_group_object without groupByColumn**: Each row creates a key-value pair; duplicate keys result if key values aren't unique
8. **allowExpressions**: For column extraction ONLY (e.g., \`json_extract\`), NOT aggregate functions — use \`aggregateFunction\` param instead
9. **sqlite_json_normalize_column**: Defaults to \`preserve\` (maintains original format); use \`outputFormat: 'text'\` to force text
10. **Fuzzy matching tokenization**: Matches WORD TOKENS by default — \`"laptop"\` matches \`"Laptop Pro 15"\` (distance 0 on first token). Use \`tokenize: false\` for full-string matching
11. **SpatiaLite distances**: \`nearest_neighbor\`/\`distance_matrix\` return CARTESIAN distance (degrees), not geodetic (km/miles)
12. **SpatiaLite buffer**: Auto-simplifies output by default (tolerance=0.0001). Use \`simplifyTolerance: 0\` to disable
13. **sqlite_stats_top_n**: Auto-excludes long-content columns (description, body, notes, etc.) when \`selectColumns\` is omitted. Use \`selectColumns\` to override
14. **CSV virtual tables**: Require ABSOLUTE file paths
15. **sqlite_create_series_table**: Creates a REGULAR table (not virtual) — use \`sqlite_drop_table\` to remove
16. **sqlite_dbstat**: \`summarize\` only works in native; WASM returns counts only
17. **PRAGMA compile options**: WASM may show FTS3, not FTS5

## WASM vs Native

| Feature                                           | Native                | WASM        | Fallback         |
| ------------------------------------------------- | --------------------- | ----------- | ---------------- |
| FTS5 full-text search                             | ✅                    | ❌          | None             |
| Transactions (7 tools)                            | ✅                    | ❌          | None             |
| Window functions (6 tools in stats group)         | ✅                    | ❌          | None             |
| SpatiaLite GIS (7 tools; 4 basic geo always work) | ✅                    | ❌          | None             |
| Backup/Restore (3 tools)                          | ✅                    | ❌          | Graceful error   |
| R-Tree spatial indexing                           | ✅                    | ❌          | Graceful error   |
| CSV virtual tables                                | ✅                    | ❌          | Graceful error   |
| generate_series                                   | JS fallback           | JS fallback | —                |
| dbstat                                            | ✅ native (per-table) | ❌          | JS (counts only) |
| soundex()                                         | ✅ native             | ❌          | JS               |

## Code Mode (1 tool)

| Tool                  | Description                                                       |
| --------------------- | ----------------------------------------------------------------- |
| \`sqlite_execute_code\` | Execute JavaScript in a sandboxed environment with \`sqlite.*\` API |

**Usage**: \`sqlite_execute_code({ code: "const tables = await sqlite.core.listTables(); return tables;" })\`
**Discover**: \`sqlite.help()\` for all groups, \`sqlite.<group>.help()\` for methods.
**Groups**: \`sqlite.core\`, \`sqlite.json\`, \`sqlite.text\`, \`sqlite.stats\`, \`sqlite.vector\`, \`sqlite.admin\`, \`sqlite.geo\`, \`sqlite.introspection\`, \`sqlite.migration\`

## Code Mode API Mapping

\`sqlite_group_action\` → \`sqlite.group.action()\` (group prefixes dropped: \`sqlite_json_insert\` → \`sqlite.json.insert()\`)

**Positional args work**: \`sqlite.core.readQuery("SELECT...")\`, \`sqlite.json.insert("docs", "data", {...})\`

**Discovery**: \`sqlite.help()\` returns all groups and methods. \`sqlite.core.help()\`, \`sqlite.json.help()\` for group-specific methods.`,
  ],
  [
    "introspection",
    `# db-mcp Help — Schema Introspection (9 tools)

All introspection tools are **read-only** — they query PRAGMAs and sqlite_master, never modify data.

## Graph Analysis (3 tools)

\`\`\`javascript
// Build FK dependency graph — nodesOnly: true for lightweight response (nodes without edges)
sqlite_dependency_graph({ includeRowCounts: true, excludeSystemTables: true });
sqlite_dependency_graph({ nodesOnly: true }); // lighter payload

// Safe DDL execution order — "create" = parents first (default), "drop" = children first
sqlite_topological_sort({ direction: "create", excludeSystemTables: true });
sqlite_topological_sort({ direction: "drop" }); // safe DROP order

// Simulate DELETE/DROP/TRUNCATE impact — shows affected tables, cascade paths, severity scoring
sqlite_cascade_simulator({ table: "users", operation: "delete" });
sqlite_cascade_simulator({ table: "users", operation: "drop", compact: true }); // compact omits path arrays
\`\`\`

## Schema Analysis (3 tools)

\`\`\`javascript
// Full schema in one call — compact: true omits column details, sections limits scope
sqlite_schema_snapshot({ sections: ["tables", "indexes"], excludeSystemTables: true });
sqlite_schema_snapshot({ compact: true }); // lighter payload

// Find constraint health issues — missing PKs, nullable FKs, unindexed FKs
sqlite_constraint_analysis({ excludeSystemTables: true });
sqlite_constraint_analysis({ table: "orders", checks: ["missing_pk", "unindexed_fk"] }); // limit scope

// Analyze DDL for SQLite-specific risks — does NOT execute the statements
sqlite_migration_risks({ statements: ["ALTER TABLE users ADD COLUMN email TEXT", "DROP TABLE old_logs"] });
\`\`\`

## Diagnostics (3 tools)

\`\`\`javascript
// Fragmentation, per-table size breakdown, optimization recommendations
sqlite_storage_analysis({ includeTableDetails: true, excludeSystemTables: true });
sqlite_storage_analysis({ limit: 10 }); // top 10 tables only

// Audit index effectiveness — find redundant, missing FK, unindexed large tables
sqlite_index_audit({ excludeSystemTables: true });
sqlite_index_audit({ table: "orders", minSeverity: "warning" }); // reduce payload

// EXPLAIN QUERY PLAN with scan-type classification and optimization suggestions (SELECT/WITH only)
sqlite_query_plan({ sql: "SELECT * FROM orders WHERE status = 'active'" });
\`\`\`

## ⚠️ Gotchas

- \`excludeSystemTables\` defaults to \`true\` — SpatiaLite system tables are hidden for cleaner output. Pass \`false\` to include them
- \`sqlite_migration_risks\` analyzes DDL text statically — it does NOT execute the statements`,
  ],
  [
    "json",
    `# db-mcp Help — JSON Operations (23 tools)

## Collection & CRUD

- \`sqlite_create_json_collection({ tableName, indexes: [{ path: "$.type" }, { path: "$.author" }] })\` — creates table with JSON indexes
- \`sqlite_json_insert({ table, column, data: { type: "article", title: "Hello", tags: ["news"] } })\` — insert JSON document
- \`sqlite_json_select({ table, column, extractPaths? })\` — select rows, optionally extract specific JSON paths
- \`sqlite_json_update({ table, column, path, value, whereClause })\` — update value at JSON path
- \`sqlite_json_query({ table, column, filterPaths: { "$.type": "article" }, selectPaths: ["$.title"] })\` — query with path-based filters and projections

## Path Operations

- \`sqlite_json_extract({ table, column, path: "$.title" })\` — extract value at path. Returns null if path doesn't exist
- \`sqlite_json_set({ table, column, path: "$.views", value: 100, whereClause: "id = 1" })\` — set value at path (creates if missing)
- \`sqlite_json_merge({ table, column, mergeData: { featured: true }, whereClause: "id = 1" })\` — merge object into existing JSON
- \`sqlite_json_remove({ table, column, path, whereClause })\` — remove key at path
- \`sqlite_json_validate_path({ path: "$.store.books[0].title" })\` — validate JSON path syntax without executing a query
- \`sqlite_json_type({ table, column, path })\` — get JSON type (null, true, false, integer, real, text, array, object)

## Array Operations

⚠️ \`json_each\` multiplies output rows — use \`limit\` param for large arrays

- \`sqlite_json_array_append({ table, column, path: "$.tags", value: "featured", whereClause: "id = 1" })\` — append to array
- \`sqlite_json_array_length({ table, column, path })\` — get array length
- \`sqlite_json_each({ table, column, path: "$.tags", limit: 50 })\` — expand array to rows

## Aggregation & Analysis

\`\`\`javascript
// Regular tables: use column names directly
sqlite_json_group_array({ table: "events", valueColumn: "user_id", groupByColumn: "event_type" });

// JSON collections: use allowExpressions with json_extract for both columns
// ⚠️ allowExpressions is for column extraction ONLY, NOT aggregate functions
// ⚠️ Without groupByColumn, each row creates a key-value pair; duplicate keys if values aren't unique
sqlite_json_group_array({
  table: "docs",
  valueColumn: "json_extract(data, '$.author')",
  groupByColumn: "json_extract(data, '$.type')",
  allowExpressions: true,
});

// For aggregate values (COUNT, SUM, AVG), use aggregateFunction parameter instead
sqlite_json_group_object({ table: "events", keyColumn: "event_type", aggregateFunction: "COUNT(*)" });
sqlite_json_group_object({ table: "orders", keyColumn: "status", aggregateFunction: "SUM(total)" });
\`\`\`

- \`sqlite_json_keys({ table, column, path? })\` — get distinct keys of JSON objects
- \`sqlite_json_pretty({ table, column, whereClause? })\` — format JSON with indentation
- \`sqlite_json_valid({ table, column })\` — check if values are valid JSON
- \`sqlite_json_analyze_schema({ table, column })\` — infer schema types

## JSONB Optimization (SQLite 3.45+)

- \`sqlite_json_storage_info({ table, column })\` — check text vs JSONB format
- \`sqlite_jsonb_convert({ table, column })\` — convert to JSONB for faster queries
- \`sqlite_json_normalize_column({ table, column, outputFormat? })\` — normalize JSON (sort keys, compact). ⚠️ Defaults to \`"preserve"\` (maintains original format); use \`outputFormat: "text"\` to force text output`,
  ],
  [
    "migration",
    `# db-mcp Help — Migration Tracking (6 tools)

⚠️ Must call \`sqlite_migration_init()\` before using any other migration tool — it creates the tracking table.

\`\`\`javascript
// Initialize tracking table (idempotent — safe to call multiple times)
sqlite_migration_init();

// Apply migration: executes SQL and records atomically. If SQL fails, no record is created
// SHA-256 dedup — submitting the same SQL twice is rejected as a duplicate
sqlite_migration_apply({
  version: "2024-01-15-add-users",
  description: "Create users table",
  migrationSql: "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE)",
  rollbackSql: "DROP TABLE users",
  sourceSystem: "agent",
  appliedBy: "claude",
});

// Record externally-applied migration (does NOT execute the SQL)
sqlite_migration_record({
  version: "2024-01-10-initial",
  description: "Initial schema (pre-existing)",
  migrationSql: "CREATE TABLE orders (...)",
  sourceSystem: "manual",
});

// Rollback by ID or version — requires rollbackSql to have been recorded
sqlite_migration_rollback({ version: "2024-01-15-add-users" });
sqlite_migration_rollback({ id: 3, dryRun: true }); // preview SQL without executing

// Query history with filters and pagination
sqlite_migration_history({ status: "applied", limit: 10 });
sqlite_migration_history({ sourceSystem: "agent", compact: true }); // compact omits hash and source system

// Summary: latest version, counts by status, unique source systems
sqlite_migration_status();
\`\`\`

## ⚠️ Gotchas

- Rollback requires \`rollbackSql\` to have been provided when the migration was recorded/applied
- Migration group is **opt-in** — not included in any shortcut except \`dev-schema\` and \`full\``,
  ],
  [
    "stats",
    `# db-mcp Help — Statistical Analysis (13 core + 6 window)

## Core Statistics (always available)

\`\`\`javascript
sqlite_stats_basic({ table: "employees", column: "salary" }); // count, sum, avg, min, max
sqlite_stats_count({ table: "orders", column: "status", distinct: true }); // count rows, optionally distinct
sqlite_stats_group_by({ table: "orders", column: "total", groupBy: "status" }); // aggregate by group
sqlite_stats_percentile({ table: "sales", column: "revenue", percentiles: [25, 50, 75, 90] });
sqlite_stats_histogram({ table: "products", column: "price", buckets: 10 });
sqlite_stats_correlation({ table: "data", column1: "x", column2: "y" }); // Pearson coefficient
sqlite_stats_distinct({ table: "orders", column: "status" }); // distinct values
sqlite_stats_summary({ table: "data", columns: ["price", "quantity", "discount"] }); // multi-column summary
sqlite_stats_frequency({ table: "orders", column: "status" }); // frequency distribution
sqlite_stats_regression({ table: "data", xColumn: "year", yColumn: "revenue" }); // linear
sqlite_stats_regression({ table: "data", xColumn: "year", yColumn: "revenue", degree: 2 }); // quadratic
sqlite_stats_outliers({ table: "sales", column: "amount", method: "iqr" }); // or "zscore". Use maxOutliers to limit payload
sqlite_stats_hypothesis({ table: "samples", column: "value", testType: "ttest_one", expectedMean: 100 });
\`\`\`

⚠️ \`sqlite_stats_top_n\` — always use \`selectColumns\` to avoid returning all columns (large payloads with text fields):

\`\`\`javascript
sqlite_stats_top_n({
  table: "products",
  column: "price",
  n: 10,
  selectColumns: ["id", "name", "price"],
});
\`\`\`

## Window Functions (6 tools, Native only)

\`\`\`javascript
sqlite_window_row_number({ table: "employees", orderBy: "hire_date", partitionBy: "department" });
sqlite_window_rank({ table: "sales", orderBy: "revenue DESC", partitionBy: "region", rankType: "dense_rank" });
sqlite_window_lag_lead({ table: "sales", orderBy: "date", column: "revenue", partitionBy: "region" }); // access previous/next row values
sqlite_window_running_total({ table: "transactions", column: "amount", orderBy: "date" });
sqlite_window_moving_avg({ table: "stock_prices", column: "close_price", orderBy: "date", windowSize: 7 });
sqlite_window_ntile({ table: "employees", orderBy: "salary DESC", buckets: 4, partitionBy: "department" }); // quartiles
\`\`\``,
  ],
  [
    "text",
    `# db-mcp Help — Text Processing & FTS5

## Full-Text Search / FTS5 (4 tools, Native only)

\`\`\`javascript
// Create FTS5 table with triggers for auto-sync on future changes
sqlite_fts_create({ tableName: "articles_fts", sourceTable: "articles", columns: ["title", "content"] });
sqlite_fts_rebuild({ table: "articles_fts" }); // ⚠️ Required: populate index with existing data

// FTS5 uses AND by default: "machine learning" = rows containing BOTH words
// Use OR explicitly: "machine OR learning" for rows containing EITHER word
sqlite_fts_search({ table: "articles_fts", query: "machine learning", limit: 10 });
sqlite_fts_match_info({ table: "articles_fts", query: "machine learning" }); // bm25 ranking info
\`\`\`

⚠️ FTS5 virtual tables (\`*_fts\`) and shadow tables (\`*_fts_*\`) are hidden from \`sqlite_list_tables\` for cleaner output

## Text Processing (13 tools)

\`\`\`javascript
// Regex patterns: ⚠️ Double-escape backslashes (\\\\) when passing through JSON/MCP
sqlite_regex_match({ table: "logs", column: "message", pattern: "ERROR:\\\\\\\\s+(\\\\\\\\w+)" });
sqlite_regex_extract({ table: "users", column: "email", pattern: "@([a-zA-Z0-9.-]+)", groupIndex: 1 });

// Text manipulation
sqlite_text_split({ table: "users", column: "email", delimiter: "@" }); // split into parts array
sqlite_text_concat({ table: "users", columns: ["first_name", "last_name"], separator: " " });
sqlite_text_replace({ table: "docs", column: "content", search: "old", replacement: "new" });
sqlite_text_trim({ table: "users", column: "name" }); // trim whitespace
sqlite_text_case({ table: "products", column: "name", mode: "upper" }); // or "lower"
sqlite_text_substring({ table: "codes", column: "value", start: 1, length: 3 }); // extract substring
sqlite_text_normalize({ table: "docs", column: "content", mode: "strip_accents" }); // or nfc, nfd, nfkc, nfkd

// Validation patterns: email, phone, url, uuid, ipv4, custom
sqlite_text_validate({ table: "users", column: "email", pattern: "email" });
sqlite_text_validate({ table: "data", column: "field", pattern: "custom", customPattern: "^[A-Z]{2}[0-9]{4}$" });

// Fuzzy matching — matches WORD TOKENS by default (not entire value)
// "laptop" matches "Laptop Pro 15" (distance 0 on first token). Use tokenize: false for full-string matching.
sqlite_fuzzy_match({ table: "products", column: "name", search: "laptop", maxDistance: 2 });
sqlite_fuzzy_match({ table: "products", column: "name", search: "laptob", maxDistance: 2, tokenize: false }); // full value

// Phonetic matching — finds words that sound alike (matches against any word in value)
// Use includeRowData: false for lighter payloads when only matching values are needed
sqlite_phonetic_match({ table: "products", column: "name", search: "laptop", algorithm: "soundex" });
sqlite_phonetic_match({ table: "products", column: "name", search: "laptop", includeRowData: false }); // lighter

// Advanced search — combines exact, fuzzy, and phonetic techniques
// fuzzyThreshold: 0.3-0.4 = loose matching (more results), 0.6-0.8 = strict matching (fewer results)
sqlite_advanced_search({
  table: "products", column: "name", searchTerm: "laptop",
  techniques: ["exact", "fuzzy", "phonetic"], fuzzyThreshold: 0.4,
});
\`\`\``,
  ],
  [
    "vector",
    `# db-mcp Help — Vector/Semantic Search (11 tools)

\`\`\`javascript
// Create vector table with metadata columns
sqlite_vector_create_table({ tableName: "docs", dimensions: 384, additionalColumns: [{ name: "content", type: "TEXT" }] });

// Store vectors (single and batch)
sqlite_vector_store({ table: "docs", idColumn: "id", vectorColumn: "emb", id: 1, vector: [...] });
sqlite_vector_batch_store({ table: "docs", idColumn: "id", vectorColumn: "emb", items: [{ id: 1, vector: [...] }, { id: 2, vector: [...] }] });

// Search vectors (returnColumns omits vector data from results for smaller payloads)
sqlite_vector_search({ table: "docs", vectorColumn: "emb", queryVector: [...], limit: 10, returnColumns: ["id", "title"] });

// Retrieve and delete vectors
// Note: sqlite_vector_get returns parsed 'vector' array + raw JSON string in 'metadata' for flexibility
sqlite_vector_get({ table: "docs", idColumn: "id", vectorColumn: "emb", id: 1 });
sqlite_vector_delete({ table: "docs", idColumn: "id", ids: [1, 2, 3] });

// Vector metadata
sqlite_vector_count({ table: "docs" }); // or with dimensions filter: { table: "docs", dimensions: 384 }
sqlite_vector_dimensions({ table: "docs", vectorColumn: "emb" });
sqlite_vector_stats({ table: "docs", vectorColumn: "emb" }); // magnitude min/max/avg

// Utility tools for preprocessing
sqlite_vector_normalize({ vector: [3, 4, 0, 0] }); // returns unit vector [0.6, 0.8, 0, 0]
sqlite_vector_distance({ vector1: [...], vector2: [...], metric: "cosine" }); // or "euclidean", "dot"
\`\`\``,
  ],
]);
