/**
 * Generates src/constants/ServerInstructions.ts from markdown source files.
 *
 * Reads three markdown files (essential, filtering, tool-reference),
 * escapes backticks and template expressions, and wraps them in a
 * TypeScript module with tiered instruction constants and dynamic logic.
 *
 * Uses string concatenation (not template literals) to build the output,
 * because the output itself contains template literals with interpolation.
 *
 * Usage: node scripts/generate-server-instructions.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const constantsDir = resolve(projectRoot, "src/constants");

// Read markdown sources
const essentialMd = readFileSync(
  resolve(constantsDir, "essential-instructions.md"),
  "utf-8",
);
const filteringMd = readFileSync(
  resolve(constantsDir, "filtering-instructions.md"),
  "utf-8",
);
const toolRefMd = readFileSync(
  resolve(constantsDir, "tool-reference.md"),
  "utf-8",
);

/**
 * Escape content for use inside a JS/TS template literal.
 * Handles: backslashes, backticks, and template expressions (${).
 */
function escapeForTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

const essentialEscaped = escapeForTemplateLiteral(essentialMd);
const filteringEscaped = escapeForTemplateLiteral(filteringMd);
const toolRefEscaped = escapeForTemplateLiteral(toolRefMd);

// Use backtick char for building string to avoid nesting issues
const BT = "`";
const BT3 = "```";

// Build the TypeScript file using string concatenation
const lines: string[] = [];

lines.push("/**");
lines.push(" * Server instructions for db-mcp (SQLite MCP Server).");
lines.push(" *");
lines.push(
  " * \u26a0\ufe0f  AUTO-GENERATED \u2014 DO NOT EDIT THIS FILE DIRECTLY",
);
lines.push(" *     Edit src/constants/*.md files instead,");
lines.push(" *     then run: npm run generate:instructions");
lines.push(" *");
lines.push(
  " * These instructions are automatically sent to MCP clients during initialization,",
);
lines.push(" * providing guidance for AI agents on tool usage.");
lines.push(" *");
lines.push(" * Optimized for token efficiency with tiered instruction levels.");
lines.push(" */");
lines.push("");
lines.push('import type { ToolGroup } from "../types/index.js";');
lines.push(
  'import { TOOL_GROUPS, ALL_TOOL_GROUPS } from "../filtering/ToolConstants.js";',
);
lines.push("");
lines.push("/**");
lines.push(" * Resource definition for instruction generation");
lines.push(" */");
lines.push("export interface ResourceDefinition {");
lines.push("  uri: string;");
lines.push("  name: string;");
lines.push("  description?: string;");
lines.push("}");
lines.push("");
lines.push("/**");
lines.push(" * Prompt definition for instruction generation");
lines.push(" */");
lines.push("export interface PromptDefinition {");
lines.push("  name: string;");
lines.push("  description?: string;");
lines.push("}");
lines.push("");
lines.push("/**");
lines.push(" * Instruction detail level for token efficiency");
lines.push(
  " * - essential: ~200 tokens - Core behaviors only (for token-constrained clients)",
);
lines.push(
  " * - standard: ~400 tokens - + Tool filtering and groups (default)",
);
lines.push(" * - full: ~600 tokens - + Complete tool/resource reference");
lines.push(" */");
lines.push('export type InstructionLevel = "essential" | "standard" | "full";');
lines.push("");
lines.push("/**");
lines.push(" * Essential behavioral guidance (~200 tokens)");
lines.push(" * Core patterns every AI agent should follow.");
lines.push(" */");
lines.push(
  "const ESSENTIAL_INSTRUCTIONS = " + BT + essentialEscaped + BT + ";",
);
lines.push("");
lines.push("/**");
lines.push(" * Tool filtering instructions (~150 additional tokens)");
lines.push(" */");
lines.push(
  "const FILTERING_INSTRUCTIONS = " + BT + "\\n" + filteringEscaped + BT + ";",
);
lines.push("");
lines.push("/**");
lines.push(" * Tool reference - comprehensive usage examples");
lines.push(" */");
lines.push("const TOOL_REFERENCE = " + BT + "\\n" + toolRefEscaped + BT + ";");
lines.push("");
lines.push("/**");
lines.push(
  " * Generate dynamic instructions based on enabled tools, resources, and prompts",
);
lines.push(" *");
lines.push(" * @param enabledTools - Set of enabled tool names");
lines.push(" * @param resources - Available resource definitions");
lines.push(" * @param prompts - Available prompt definitions");
lines.push(" * @param level - Instruction detail level (default: 'standard')");
lines.push(" */");
lines.push("export function generateInstructions(");
lines.push("  enabledTools: Set<string>,");
lines.push("  _resources: ResourceDefinition[],");
lines.push("  prompts: PromptDefinition[],");
lines.push('  level: InstructionLevel = "standard",');
lines.push("): string {");
lines.push("  let instructions = ESSENTIAL_INSTRUCTIONS;");
lines.push("");
lines.push("  // Standard and full levels include filtering patterns");
lines.push('  if (level === "standard" || level === "full") {');
lines.push("    instructions += FILTERING_INSTRUCTIONS;");
lines.push("  }");
lines.push("");
lines.push("  // Full level includes complete tool reference");
lines.push('  if (level === "full") {');
lines.push("    instructions += TOOL_REFERENCE;");
lines.push("");
lines.push("    // Add active tools summary");
lines.push("    const activeGroups = getActiveToolGroups(enabledTools);");
lines.push("    if (activeGroups.length > 0) {");
lines.push(
  "      instructions += " +
    BT +
    "\\n## Active Tools (${String(enabledTools.size)})\\n" +
    BT +
    ";",
);
lines.push("      for (const { group, tools } of activeGroups) {");
lines.push(
  "        instructions += " +
    BT +
    "**${group}**: ${tools.map((t) => " +
    BT +
    "\\\\\\`${t}\\\\\\`" +
    BT +
    ').join(", ")}\\n' +
    BT +
    ";",
);
lines.push("      }");
lines.push("    }");
lines.push("");
lines.push("    // Add prompts section");
lines.push("    if (prompts.length > 0) {");
lines.push(
  "      instructions += " +
    BT +
    "\\n## Prompts (${String(prompts.length)})\\n" +
    BT +
    ";",
);
lines.push(
  '      instructions += "Pre-built templates and guided workflows:\\n";',
);
lines.push("      for (const prompt of prompts) {");
lines.push(
  "        instructions += " +
    BT +
    '- \\\\\\`${prompt.name}\\\\\\` - ${prompt.description ?? ""}\\n' +
    BT +
    ";",
);
lines.push("      }");
lines.push("    }");
lines.push("  }");
lines.push("");
lines.push("  return instructions;");
lines.push("}");
lines.push("");
lines.push("/**");
lines.push(" * Get active tool groups with their enabled tools");
lines.push(" */");
lines.push("function getActiveToolGroups(");
lines.push("  enabledTools: Set<string>,");
lines.push("): { group: ToolGroup; tools: string[] }[] {");
lines.push(
  "  const activeGroups: { group: ToolGroup; tools: string[] }[] = [];",
);
lines.push("");
lines.push("  for (const group of ALL_TOOL_GROUPS) {");
lines.push("    const allTools = TOOL_GROUPS[group];");
lines.push(
  "    const enabledInGroup = allTools.filter((tool) => enabledTools.has(tool));",
);
lines.push("    if (enabledInGroup.length > 0) {");
lines.push("      activeGroups.push({ group, tools: enabledInGroup });");
lines.push("    }");
lines.push("  }");
lines.push("");
lines.push("  return activeGroups;");
lines.push("}");
lines.push("");
lines.push("/**");
lines.push(" * Static instructions for backward compatibility");
lines.push(
  " * @deprecated Use generateInstructions() instead for dynamic content",
);
lines.push(" */");
lines.push("export const SERVER_INSTRUCTIONS =");
lines.push("  ESSENTIAL_INSTRUCTIONS + FILTERING_INSTRUCTIONS;");
lines.push("");

const tsContent = lines.join("\n");
const tsPath = resolve(constantsDir, "ServerInstructions.ts");
writeFileSync(tsPath, tsContent, "utf-8");

process.stderr.write(
  [
    "",
    "\u2705 Generated ServerInstructions.ts (" +
      tsContent.length.toLocaleString() +
      " bytes) from markdown sources:",
    "   essential-instructions.md (" +
      essentialMd.length.toLocaleString() +
      " bytes)",
    "   filtering-instructions.md (" +
      filteringMd.length.toLocaleString() +
      " bytes)",
    "   tool-reference.md (" + toolRefMd.length.toLocaleString() + " bytes)",
    "",
  ].join("\n"),
);
