name: E2E Tests

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Rebuild better-sqlite3 (explicitly allowed)
        run: npm rebuild better-sqlite3 --ignore-scripts=false

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build
        run: npm run build

      - name: Seed test database
        run: sqlite3 test-server/test.db < test-server/test-database.sql

      - name: Run E2E tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        if: ${{ failure() }}
        with:
          name: playwright-report-${{ github.run_id }}
          path: playwright-report/
          if-no-files-found: warn
          retention-days: 1
