name: Secret Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

permissions:
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: TruffleHog Secret Scanning
        uses: trufflesecurity/trufflehog@eccbca730d4d5b97b174b46501fa1187c7905f66 # v3.81.0
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha || github.event.before || github.event.repository.default_branch }}
          head: HEAD

      - name: GITLEAKS Secret Scanning
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        timeout-minutes: 10
